const loginActionTypes = {
  GET_OTP: 'GET_OTP',
  GET_OTP_SUCCEEDED: 'GET_OTP_SUCCEEDED',
  GET_OTP_FAILED: 'GET_OTP_FAILED',

  RESEND_OTP: 'RESEND_OTP',
  RESEND_OTP_SUCCEEDED: 'RESEND_OTP_SUCCEEDED',
  RESEND_OTP_FAILED: 'RESEND_OTP_FAILED',
};

export default loginActionTypes;
